[tool.bumpversion]
current_version = "1.2.1"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = true
sign_tags= false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = "uv.lock"

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "src/emerge/__init__.py"

[[tool.bumpversion.files]]
filename = "examples/demo0_parallel_plate.py"

[[tool.bumpversion.files]]
filename = "examples/demo1_stepped_imp_filter.py"

[[tool.bumpversion.files]]
filename = "examples/demo2_combline_filter.py"

[[tool.bumpversion.files]]
filename = "examples/demo3_coupled_line_filter.py"

[[tool.bumpversion.files]]
filename = "examples/demo4_patch_antenna.py"

[[tool.bumpversion.files]]
filename = "examples/demo5_revolve.py"

[[tool.bumpversion.files]]
filename = "examples/demo6_striplines_with_vias.py"

[[tool.bumpversion.files]]
filename = "examples/demo7_periodic_cells.py"

[[tool.bumpversion.files]]
filename = "examples/demo8_waveguide_bpf_synthesis.py"

[[tool.bumpversion.files]]
filename = "examples/demo9_dielectric_resonator.py"

[[tool.bumpversion.files]]
filename = "examples/demo10_sgh.py"

[[tool.bumpversion.files]]
filename = "examples/demo11_lumped_element_filter.py"

[[tool.bumpversion.files]]
filename = "examples/demo12_mode_alignment.py"

[[tool.bumpversion.files]]
filename = "examples/demo13_helix_antenna.py"

[[tool.bumpversion.files]]
filename = "examples/demo14_boundary_selection.py"

[[tool.bumpversion.files]]
filename = "examples/demo15_strip_slotline_transition.py"

[[tool.bumpversion.files]]
filename = "examples/demo16_differential_common_mode.py"

[[tool.bumpversion.files]]
filename = "examples/demo17_step_import.py"